include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    always_use_package_imports: ignore
    lines_longer_than_80_chars: ignore
    document_ignores: ignore
